// packages/next-frontend/app/systems/page.tsx
"use client"

import Image from "next/image"
import Link from "next/link"
import { MoreHorizontal, ArrowRight } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"


const statusTypes = ["Active", "Offline", "Paused"] as const
type StatusType = typeof statusTypes[number]

const getStatusVariant = (status: StatusType) => {
  switch (status) {
    case 'Active':
      return 'outline'
    case 'Offline':
      return 'default'
    case 'Paused':
      return 'secondary'
  }
}

interface SystemsType {
  id: string,
  name: string,
  status: StatusType,
  location: string,
  image: string,
  lastCheck: string
}

const systems: SystemsType[] = [
  {
    id: "vp1",
    name: "VisioPointer® 1",
    status: "Active",
    location: "Production Line 1",
    image: "/placeholder.svg",
    lastCheck: "2 minutes ago"
  },
  {
    id: "vc1",
    name: "VisioCompact® 1",
    status: "Active",
    location: "Assembly Area A",
    image: "/placeholder.svg",
    lastCheck: "5 minutes ago"
  },
  {
    id: "360i1",
    name: "360 Inspector® 1",
    status: "Active",
    location: "Quality Control Station",
    image: "/placeholder.svg",
    lastCheck: "1 minute ago"
  },
  {
    id: "si1",
    name: "SmartInspector® 1",
    status: "Paused",
    location: "Packaging Line 2",
    image: "/placeholder.svg",
    lastCheck: "10 minutes ago"
  },
  {
    id: "vp2",
    name: "VisioPointer® 2",
    status: "Paused",
    location: "Production Line 2",
    image: "/placeholder.svg",
    lastCheck: "15 minutes ago"
  },
  {
    id: "vc2",
    name: "VisioCompact® 2",
    status: "Active",
    location: "Assembly Area B",
    image: "/placeholder.svg",
    lastCheck: "8 minutes ago"
  },
  {
    id: "vp2",
    name: "VisioPointer® 3",
    status: "Paused",
    location: "Production Line 2",
    image: "/placeholder.svg",
    lastCheck: "15 minutes ago"
  },
  {
    id: "vc2",
    name: "VisioPointer® 4",
    status: "Offline",
    location: "Assembly Area B",
    image: "/placeholder.svg",
    lastCheck: "5 hours ago"
  }
]

export default function Component() {
  return (<>
    <Tabs defaultValue="All">
      <TabsList>
        <TabsTrigger value="All">All</TabsTrigger>
        <TabsTrigger value="Active">Active</TabsTrigger>
        <TabsTrigger value="Paused">Paused</TabsTrigger>
        <TabsTrigger value="Offline">Offline</TabsTrigger>
      </TabsList>

    <Card className="w-full">
      <CardHeader>
        <CardTitle>Production Systems</CardTitle>
        <CardDescription>
          Monitor and manage your production systems across different factory areas.
        </CardDescription>
      </CardHeader>
      <CardContent>
      <TabsContent value="All">       
         <SystemsTable systems={systems}></SystemsTable>
      </TabsContent>
      <TabsContent value="Active">       
         <SystemsTable systems={systems.filter(({status}) => status == "Active")}></SystemsTable>
      </TabsContent>
      <TabsContent value="Paused">       
         <SystemsTable systems={systems.filter(({status}) => status == "Paused")}></SystemsTable>
      </TabsContent>
      <TabsContent value="Offline">       
         <SystemsTable systems={systems.filter(({status}) => status == "Offline")}></SystemsTable>
      </TabsContent>

      </CardContent>
      <CardFooter className="flex justify-between">
        <div className="text-xs text-muted-foreground">
          Showing <strong>{systems.length}</strong> of <strong>{systems.length}</strong> systems
        </div>
        <Button variant="outline" size="sm" asChild>
          <Link href="/systems">
            View All Systems
            <ArrowRight className="ml-2 h-4 w-4" />
          </Link>
        </Button>
      </CardFooter>
    </Card>
    </Tabs>

  </>)
}


function SystemsTable({systems}: {systems: SystemsType[]}) {
  return (<>
    <div className="overflow-x-auto">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="w-[100px] hidden md:table-cell">
              <span className="sr-only">Image</span>
            </TableHead>
            <TableHead>Name</TableHead>
            <TableHead className="hidden md:table-cell">Status</TableHead>
            <TableHead className="hidden md:table-cell">Location</TableHead>
            <TableHead className="hidden md:table-cell">Last Check</TableHead>
            <TableHead >Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {systems.map((system) => (
            <TableRow key={system.id}>
              <TableCell className="hidden md:table-cell">
                <Image
                  alt={`${system.name} icon`}
                  className="aspect-square rounded-md object-cover"
                  height="64"
                  src={system.image}
                  width="64"
                />
              </TableCell>
              <TableCell className="font-medium">{system.name}</TableCell>
              <TableCell className="">
                <Badge variant={getStatusVariant(system.status)}>
                  {system.status}
                </Badge>
              </TableCell>
              <TableCell className="hidden md:table-cell">{system.location}</TableCell>
              <TableCell className="hidden md:table-cell">{system.lastCheck}</TableCell>
              <TableCell className="text-right">
                <div className="flex items-center justify-end gap-2">
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button aria-haspopup="true" size="icon" variant="ghost">
                        <MoreHorizontal className="h-4 w-4" />
                        <span className="sr-only">Actions</span>
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuLabel>Actions</DropdownMenuLabel>
                      <DropdownMenuItem asChild>
                        <Link href={`/systems/monitoring/abcd`}>
                          View Details
                        </Link>
                      </DropdownMenuItem>
                      <DropdownMenuItem>Restart System</DropdownMenuItem>
                      <DropdownMenuItem>Update Configuration</DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  </>)
}

// services/frontend/src/routes/(app)/organization/[organizationId]/systems/+page.svelte
<script lang="ts">
	import ArrowRight from 'lucide-svelte/icons/arrow-right';
	import ArrowDownUp from 'lucide-svelte/icons/arrow-down-up';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import * as Card from '$lib/components/ui/card';
	import * as Table from '$lib/components/ui/table';
	import { goto } from '$app/navigation';
	import { writable } from 'svelte/store';
	import { systems } from '$lib/stores/systems';

	type System = {
		id: string;
		name: string;
		health: 'Healthy' | 'At Risk' | 'Critical';
		status: 'Active' | 'Offline' | 'Paused';
		type: string;
		lastCheck: string;
		image: string;
	};

	function getStatusVariant(status: System['status']) {
		switch (status) {
			case 'Active':
				return 'outline';
			case 'Offline':
				return 'outline';
			case 'Paused':
				return 'secondary';
		}
	}

	function getHealthVariant(health: System['health']) {
		switch (health) {
			case 'Healthy':
				return 'healthy';
			case 'At Risk':
				return 'warning';
			case 'Critical':
				return 'critical';
		}
	}

	const parseTime = (timeStr: string): number => {
		const [value, unit] = timeStr.split(' ');
		const multipliers = { minute: 1, hour: 60, day: 1440 };
		return parseInt(value) * (multipliers[unit.replace(/s$/, '') as keyof typeof multipliers] || 0);
	};

	const sortedSystems = writable<System[]>(systems);
	let currentOrder = 1;

	type SortKey = 'name' | 'health' | 'status' | 'type' | 'lastCheck';

	const sortSystems = (key: SortKey) => {
		sortedSystems.update((systems) => {
			const sorted = [...systems].sort((a, b) => {
				if (key === 'lastCheck') {
					return (parseTime(a[key]) - parseTime(b[key])) * currentOrder;
				}
				return (a[key] > b[key] ? 1 : -1) * currentOrder;
			});
			currentOrder *= -1;
			return sorted;
		});
	};

	let name = 'User'; // Replace with actual user name

	const headers: { label: string; key: SortKey }[] = [
		{ label: 'Name', key: 'name' },
		{ label: 'Health', key: 'health' },
		{ label: 'Status', key: 'status' },
		{ label: 'Location', key: 'type' },
		{ label: 'Last Check', key: 'lastCheck' }
	];
</script>

<div class="md:container">
	<Card.Root class="w-full">
		<Card.Header class="flex gap-4 md:flex-row justify-between">
			<div>
				<Card.Title>Hello {name}</Card.Title>
				<Card.Description>
					Monitor and manage your vision systems across different factory areas.
				</Card.Description>
			</div>
		</Card.Header>
		<Card.Content>
			<div class="overflow-x-auto">
				<Table.Root>
					<Table.Header>
						<Table.Row>
							<Table.Head class="hidden w-[100px] md:table-cell">
								<span class="sr-only">Image</span>
							</Table.Head>
							{#each headers as { label, key }, i}
								<Table.Head class={i > 2 ? 'hidden md:table-cell' : ''}>
									<button on:click={() => sortSystems(key)}>
										{label}
										<ArrowDownUp class="w-3 h-3 inline-block ml-1" />
									</button>
								</Table.Head>
							{/each}
						</Table.Row>
					</Table.Header>
					<Table.Body>
						{#each $sortedSystems as system (system.id)}
							<Table.Row
								on:click={() => goto(`./systems/${system.id}`)}
								class="hover:bg-muted cursor-pointer"
							>
								<Table.Cell class="hidden md:table-cell">
									<img
										alt="{system.name} icon"
										class="aspect-square rounded-md object-cover"
										height="64"
										src={system.image}
										width="64"
									/>
								</Table.Cell>
								<Table.Cell class="font-medium">{system.name}</Table.Cell>
								<Table.Cell>
									<Badge variant={getHealthVariant(system.health)}>
										{system.health}
									</Badge>
								</Table.Cell>
								<Table.Cell>
									<Badge variant={getStatusVariant(system.status)}>
										{system.status}
									</Badge>
								</Table.Cell>
								<Table.Cell class="hidden md:table-cell">{system.type}</Table.Cell>
								<Table.Cell class="hidden md:table-cell">{system.lastCheck}</Table.Cell>
							</Table.Row>
						{/each}
					</Table.Body>
				</Table.Root>
			</div>
		</Card.Content>
		<Card.Footer class="flex justify-between">
			<div class="text-muted-foreground text-xs">
				Showing <strong>{$sortedSystems.length}</strong> of <strong>{systems.length}</strong> systems
			</div>
			<Button href="/systems" variant="outline" size="sm">
				View All Systems
				<ArrowRight class="ml-2 h-4 w-4" />
			</Button>
		</Card.Footer>
	</Card.Root>
</div>
